# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default=None, max_length=500)),
                ('area_name', models.CharField(default=None, max_length=500)),
                ('address', models.CharField(default=None, max_length=500)),
                ('amenities', models.CharField(default=None, max_length=700)),
                ('furnishing', models.CharField(default=None, max_length=500)),
                ('available_for', models.CharField(default=None, max_length=500)),
                ('price', models.IntegerField(default=None)),
                ('bedroom_no', models.IntegerField(default=None)),
                ('house_type', models.CharField(default=None, max_length=500)),
                ('add_to_bookmark', models.BooleanField(default=False)),
                ('posted_by', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.CharField(default=None, max_length=100)),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(default=None, max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(default=None, max_length=100)),
                ('contact_no', models.CharField(default=None, max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='sessiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomrentportal.UserModel'),
        ),
    ]
