# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomrentportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('house_id', models.CharField(default=0, max_length=100)),
                ('add_to_bookmark', models.BooleanField(default=False)),
            ],
        ),
    ]
