# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomrentportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contact_no',
            field=models.CharField(default='9680256373', max_length=15),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='abc', max_length=500),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='abc123', max_length=100),
        ),
    ]
