# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomrentportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('house_id', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
