# Generated by Django 2.0.6 on 2018-06-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomrentportal', '0002_addbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
