# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomrentportal', '0002_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='email_id',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='bookmarkobj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roomrentportal.UserModel'),
        ),
    ]
