# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomrentportal', '0003_auto_20180429_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmarkobj',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='house_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
